In [1]:
import pickle
import pandas as pd
import numpy as np
import random

In [2]:
# Load All Files

with open('pipeline.pkl', 'rb') as file_1:
  model = pickle.load(file_1)

# Dummy Data for Inference

In [3]:
# Pengaturan Seed
seed_value = 10
random.seed(seed_value)
np.random.seed(seed_value)
n = 100

checking_status_options = ['no checking', '<0','0<=X<200','>=200']
checking_status = random.choices(checking_status_options, k=n)

credit_history_options = ['existing paid', 'critical/other existing credit','delayed previously','all paid','no credits/all paid']
credit_history = random.choices(credit_history_options, k=n)

purpose_options = ['radio/tv', 'new car','furniture/equipment','used car','business','education','repairs','domestic appliance','other','retraining']
purpose = random.choices(purpose_options, k=n)

savings_status_options = ['<100', 'no known savings','100<=X<500','500<=X<1000','>=1000']
savings_status = random.choices(savings_status_options, k=n)

employment_options = ['1<=X<4', '>=7','4<=X<7','<1','unemployed']
employment = random.choices(employment_options, k=n)

personal_status_options = ['male single', 'female div/dep/mar','male mar/wid','male div/sep']
personal_status = random.choices(personal_status_options, k=n)

other_parties_options = ['none', 'guarantor','co applicant']
other_parties = random.choices(other_parties_options, k=n)

property_magnitude_options = ['car', 'real estate','life insurance','no known property']
property_magnitude = random.choices(property_magnitude_options, k=n)

other_payment_plans_options = ['none', 'bank','stores']
other_payment_plans = random.choices(other_payment_plans_options, k=n)

housing_options = ['own', 'rent','for free']
housing = random.choices(housing_options, k=n)

job_options = ['skilled', 'unskilled resident','high qualif/self emp/mgmt','unemp/unskilled non res']
job = random.choices(job_options, k=n)

own_telephone_options = ['none', 'yes']
own_telephone = random.choices(own_telephone_options, k=n)

foreign_worker_options = ['yes', 'no']
foreign_worker = random.choices(foreign_worker_options, k=n)

duration = np.random.uniform(4,72,n)
duration = np.round(duration).astype(int)

credit_amount = np.random.uniform(250,18424,n)
credit_amount = np.round(credit_amount).astype(float)

installment_commitment = np.random.uniform(1,4,n)
installment_commitment = np.round(installment_commitment).astype(object)

residence_since = np.random.uniform(1,4,n)
residence_since = np.round(residence_since).astype(object)

age = np.random.uniform(19,75,n)
age = np.round(age).astype(int)

existing_credits = np.random.uniform(1,4,n)
existing_credits = np.round(existing_credits).astype(int)

num_dependents = np.random.uniform(1,2,n)
num_dependents = np.round(num_dependents).astype(object)



# Membuat DataFrame
data_inf = pd.DataFrame({
    'checking_status': checking_status,
    'credit_history': credit_history,
    'purpose' : purpose,
    'savings_status': savings_status,
    'employment': employment,
    'personal_status' : personal_status,
    'other_parties': other_parties,
    'property_magnitude': property_magnitude,
    'other_payment_plans': other_payment_plans,
    'housing': housing,
    'job': job,
    'own_telephone' : own_telephone,
    'foreign_worker': foreign_worker,
    'duration': duration,
    'credit_amount': credit_amount,
    'installment_commitment': installment_commitment,
    'residence_since': residence_since,
    'age': age,
    'existing_credits': existing_credits,
    'num_dependents': num_dependents
})

data_inf

,checking_status,credit_history,purpose,savings_status,employment,personal_status,other_parties,property_magnitude,other_payment_plans,housing,job,own_telephone,foreign_worker,duration,credit_amount,installment_commitment,residence_since,age,existing_credits,num_dependents
0,0<=X<200,delayed previously,used car,<100,>=7,male single,guarantor,real estate,stores,rent,skilled,yes,yes,56,10757.0,3.0,3.0,32,1,1.0
1,<0,existing paid,used car,500<=X<1000,unemployed,female div/dep/mar,co applicant,real estate,none,for free,high qualif/self emp/mgmt,yes,no,5,15769.0,3.0,2.0,62,1,2.0
2,0<=X<200,existing paid,domestic appliance,no known savings,1<=X<4,male single,co applicant,no known property,bank,for free,unemp/unskilled non res,yes,yes,47,1488.0,2.0,3.0,57,2,2.0
3,no checking,delayed previously,repairs,no known savings,<1,male single,guarantor,car,stores,for free,skilled,yes,yes,55,8692.0,4.0,3.0,59,1,1.0
4,>=200,existing paid,furniture/equipment,500<=X<1000,1<=X<4,male div/sep,co applicant,real estate,bank,own,high qualif/self emp/mgmt,none,yes,38,14461.0,2.0,3.0,67,3,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0<=X<200,all paid,other,100<=X<500,unemployed,male div/sep,guarantor,no known property,none,rent,high qualif/self emp/mgmt,none,no,38,5590.0,4.0,4.0,43,3,1.0
96,<0,existing paid,used car,>=1000,4<=X<7,female div/dep/mar,none,no known property,stores,for free,high qualif/self emp/mgmt,none,yes,70,12167.0,3.0,2.0,66,2,1.0
97,no checking,no credits/all paid,radio/tv,no known savings,1<=X<4,male div/sep,none,real estate,none,rent,unemp/unskilled non res,none,yes,34,14854.0,3.0,3.0,20,3,2.0
98,<0,no credits/all paid,retraining,500<=X<1000,4<=X<7,male mar/wid,none,life insurance,bank,for free,skilled,yes,no,26,6633.0,1.0,2.0,48,2,1.0
99,>=200,existing paid,new car,<100,unemployed,male div/sep,co applicant,car,none,own,skilled,yes,yes,39,1948.0,2.0,2.0,46,3,1.0

# Prediction

In [4]:
predict = model.predict(data_inf)
predict

array([1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0])

In [5]:
prediction = pd.DataFrame(predict,columns=['prediction'])
prediction

    prediction
0            1
1            1
2            1
3            0
4            0
..         ...
95           1
96           1
97           0
98           1
99           0

[100 rows x 1 columns]

In [6]:
data_final = pd.concat([data_inf,prediction],axis=1)
data_final

,checking_status,credit_history,purpose,savings_status,employment,personal_status,other_parties,property_magnitude,other_payment_plans,housing,...,own_telephone,foreign_worker,duration,credit_amount,installment_commitment,residence_since,age,existing_credits,num_dependents,prediction
0,0<=X<200,delayed previously,used car,<100,>=7,male single,guarantor,real estate,stores,rent,...,yes,yes,56,10757.0,3.0,3.0,32,1,1.0,1
1,<0,existing paid,used car,500<=X<1000,unemployed,female div/dep/mar,co applicant,real estate,none,for free,...,yes,no,5,15769.0,3.0,2.0,62,1,2.0,1
2,0<=X<200,existing paid,domestic appliance,no known savings,1<=X<4,male single,co applicant,no known property,bank,for free,...,yes,yes,47,1488.0,2.0,3.0,57,2,2.0,1
3,no checking,delayed previously,repairs,no known savings,<1,male single,guarantor,car,stores,for free,...,yes,yes,55,8692.0,4.0,3.0,59,1,1.0,0
4,>=200,existing paid,furniture/equipment,500<=X<1000,1<=X<4,male div/sep,co applicant,real estate,bank,own,...,none,yes,38,14461.0,2.0,3.0,67,3,2.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0<=X<200,all paid,other,100<=X<500,unemployed,male div/sep,guarantor,no known property,none,rent,...,none,no,38,5590.0,4.0,4.0,43,3,1.0,1
96,<0,existing paid,used car,>=1000,4<=X<7,female div/dep/mar,none,no known property,stores,for free,...,none,yes,70,12167.0,3.0,2.0,66,2,1.0,1
97,no checking,no credits/all paid,radio/tv,no known savings,1<=X<4,male div/sep,none,real estate,none,rent,...,none,yes,34,14854.0,3.0,3.0,20,3,2.0,0
98,<0,no credits/all paid,retraining,500<=X<1000,4<=X<7,male mar/wid,none,life insurance,bank,for free,...,yes,no,26,6633.0,1.0,2.0,48,2,1.0,1
99,>=200,existing paid,new car,<100,unemployed,male div/sep,co applicant,car,none,own,...,yes,yes,39,1948.0,2.0,2.0,46,3,1.0,0